version: "3.8"

services:
  eureka-server:
    build: ./eureka_server
    container_name: eureka_server
    ports:
      - "8761:8761"
    networks:
      - school-network

  student-service:
    build: ./micro_service1
    container_name: student_service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    networks:
      - school-network

  bus-service:
    build: ./bus_service
    container_name: bus_service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      - school-network

networks:
  school-network:
    driver: bridge
